# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set PowerShell Execution Policy
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src\MyMovieApp\MyMovieApp.csproj --no-restore
  test:
    needs: build
    runs-on: [self-hosted]
    steps:
    - name: Test
      run: dotnet test src\MyMovieTest
