name: MyMovie CI/CD

on:

  push:

    branches: [ "master" ]

  pull_request:

    branches: [ "master" ]

jobs:

  build:    

    runs-on: [self-hosted]

    steps:
    - name: Check out code 🔑
    
    - uses: actions/checkout@v1

    - name: Set up .NET Core

      uses: actions/setup-dotnet@v1

      with:

        dotnet-version: '6.0.x'

    - name: Build with dotnet 🚀

      run: dotnet build src\MyMovieApp\MyMovieApp.csproj --configuration Release
